// The symbols a sheet can use: OpenMoji's code (the SVG's name in public/openmoji), then the German and the
// English name a search finds it by. OpenMoji is CC BY-SA 4.0 and the SVGs are unchanged; see NOTICE.
export const SYMBOLS = [
  ["270F", "Bleistift, schreiben", "pencil"],
  ["1F58A", "Stift, Kugelschreiber", "pen"],
  ["1F58D", "Buntstift, malen", "crayon"],
  ["1F58C", "Pinsel", "paintbrush"],
  ["270D", "Schreibende Hand, schreiben", "writing hand"],
  ["2702", "Schere, schneiden", "scissors"],
  ["1F4CE", "Büroklammer", "paperclip"],
  ["1F4CC", "Pinnnadel", "pushpin"],
  ["1F4CF", "Lineal", "straight ruler"],
  ["1F4D0", "Geodreieck", "triangular ruler"],
  ["1F3A8", "Farbpalette, malen", "artist palette"],
  ["1F4D6", "Offenes Buch, lesen", "open book"],
  ["1F4DA", "Bücher", "books"],
  ["1F4D3", "Heft", "notebook"],
  ["1F4DD", "Notiz, aufschreiben", "memo"],
  ["1F392", "Schulranzen", "backpack"],
  ["1F3EB", "Schule", "school"],
  ["1F3E0", "Haus, Hausaufgabe", "house"],
  ["1F442", "Ohr, hören", "ear"],
  ["1F441", "Auge, schauen", "eye"],
  ["1F440", "Augen, schauen", "eyes"],
  ["1F444", "Mund, sprechen", "mouth"],
  ["1F5E3", "Sprechender Kopf, sprechen", "speaking head"],
  ["1F4AC", "Sprechblase, sprechen", "speech balloon"],
  ["1F4AD", "Gedankenblase, denken", "thought balloon"],
  ["1F9E0", "Gehirn, denken", "brain"],
  ["1F590", "Hand, melden", "hand with fingers splayed"],
  ["1F449", "Zeigefinger nach rechts", "backhand index pointing right"],
  ["1F44D", "Daumen hoch, gut", "thumbs up"],
  ["1F44F", "Klatschen, Silben", "clapping hands"],
  ["1F464", "Einzelarbeit, allein", "bust in silhouette"],
  ["1F9D1-200D-1F91D-200D-1F9D1", "Partnerarbeit, zu zweit", "people holding hands"],
  ["1F465", "Gruppenarbeit, Gruppe", "busts in silhouette"],
  ["E249", "Zusammenarbeit, Team", "collaboration"],
  ["2B50", "Stern", "star"],
  ["1F31F", "Leuchtender Stern", "glowing star"],
  ["2728", "Sternchen, Funkeln", "sparkles"],
  ["1F3C6", "Pokal", "trophy"],
  ["1F4A1", "Glühbirne, Idee, Tipp", "light bulb"],
  ["2753", "Fragezeichen, Frage", "red question mark"],
  ["2757", "Ausrufezeichen, Achtung, Merke", "red exclamation mark"],
  ["2705", "Haken, richtig", "check mark button"],
  ["274C", "Kreuz, falsch", "cross mark"],
  ["1F50D", "Lupe, suchen, forschen", "magnifying glass tilted left"],
  ["23F0", "Wecker, Zeit", "alarm clock"],
  ["231B", "Sanduhr, Zeit", "hourglass done"],
  ["1F9EE", "Rechenschieber, rechnen", "abacus"],
  ["1F3B2", "Würfel", "game die"],
  ["1F3B5", "Musiknote, singen", "musical note"],
  ["1F3A7", "Kopfhörer, anhören", "headphone"],
  ["1F4BB", "Laptop, Computer", "laptop"],
  ["1F642", "Lächelndes Gesicht, gut", "slightly smiling face"],
  ["1F610", "Neutrales Gesicht, mittel", "neutral face"],
  ["1F641", "Trauriges Gesicht, schwer", "slightly frowning face"],
  ["2764", "Herz", "red heart"],
  ["1F340", "Kleeblatt, Glück", "four leaf clover"],
  ["1F333", "Baum", "deciduous tree"],
  ["1F33B", "Sonnenblume", "sunflower"],
  ["2600", "Sonne", "sun"],
  ["1F308", "Regenbogen", "rainbow"],
];
